### ISSUE TITLE
error in setup: can't find distutils

### ISSUE THREAD

**Issue by kusosuha6vt** [X0R0X/cli-torrent-dl#32]
```
~/cli-torrent-dl$ ./setup.sh 
Delete and re-install virtualenv? [y/N]: y
created virtual environment CPython3.8.14.final.0-64 in 91ms
  creator CPython3Posix(dest=/home/dnesterov/.config/torrentdl/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/dnesterov/.local/share/virtualenv)
    added seed packages: pip==22.0.2, setuptools==59.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Traceback (most recent call last):
  File "/home/dnesterov/.config/torrentdl/.venv/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
  File "/home/dnesterov/.config/torrentdl/.venv/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/dnesterov/.config/torrentdl/.venv/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/dnesterov/.config/torrentdl/.venv/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/dnesterov/.config/torrentdl/.venv/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/home/dnesterov/.config/torrentdl/.venv/lib/python3.8/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/home/dnesterov/.config/torrentdl/.venv/lib/python3.8/site-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/home/dnesterov/.config/torrentdl/.venv/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/home/dnesterov/.config/torrentdl/.venv/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 39, in <module>
    from pip._internal.locations import get_major_minor_version
  File "/home/dnesterov/.config/torrentdl/.venv/lib/python3.8/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/home/dnesterov/.config/torrentdl/.venv/lib/python3.8/site-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'
```

**Comment by Mr-ROPer** [comment]
Does your system have distutils installed for 3.8? Some distributions, like Ubuntu iirc, don’t bundle it with standard Python.

**Comment by X0R0X** [comment]
Hello, sorry for the delay, hadn't have a time for a hobby projects for a while :( Mr-Roper was right on track, you can fix this (on debian based system) with $ sudo apt install python3.10-distutils . If You happen to use older distro(s), you first need to add official python ppa: $ sudo add-apt-repository ppa:deadsnakes/ppa . Same goes for python 11, etc, of course.
Cheers !.
