### ISSUE TITLE
Search throws error

### ISSUE THREAD

**Issue by TheCheddarCheese** [X0R0X/cli-torrent-dl#39]
When I tun `tordl -t` I get this error:
```
Running test: engines_mod.Dl1337xto [1337x]...
Running test: engines_mod.GloTorrents [Glo]...
Running test: engines_mod.KickAssTorrents [KAT]...
Running test: engines_mod.LimeTorrents [Lime]...
Running test: engines_mod.NyaaTracker [Nyaa]...
Running test: engines_mod.TorrentGalaxy [TGx]...
Running test: engines_mod.TpbParty [TPB]...
Traceback (most recent call last):
  File "/home/saki/Downloads/cli-torrent-dl/tordl.py", line 227, in <module>
    func.test_search_engines(parsed_args.test_all)
  File "/home/saki/Downloads/cli-torrent-dl/tordl/func.py", line 74, in test_search_engines
    loop.run_until_complete(test.run())
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/saki/Downloads/cli-torrent-dl/tordl/core.py", line 496, in run
    await asyncio.wait(futures)
  File "/usr/lib/python3.12/asyncio/tasks.py", line 461, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
sys:1: RuntimeWarning: coroutine 'SearchEngineTest._on_results_fetched' was never awaited
```

OS: Arch Linux
Python ver: 3.12.6

**Comment by X0R0X** [comment]
Fixed.
